
default: &default
  adapter: postgresql
  encoding: unicode
  host: db #<= 追加
  username: postgres #<= 追加
  password: password #<= 追加
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: airbnb_clone_ina86_development

test:
  <<: *default
  database: airbnb_clone_ina86_test

production:
  <<: *default
  database: airbnb_clone_ina86_production
  username: airbnb_clone_ina86
  password: <%= ENV["AIRBNB_CLONE_INA86_DATABASE_PASSWORD"] %>
